wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657112148
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      - 60
      2:
      - 1
      - 37
      - 41
      - 55
      - 60
      3:
      - 2
      - 5
      4: 3.8.10
      5: 0.12.18
      8:
      - 5
backbone:
  desc: null
  value: w48
batch_size:
  desc: null
  value: 16
crop_size:
  desc: null
  value: 512
ignore_bg:
  desc: null
  value: true
keep_ratio:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 1.0e-08
