wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1654829670
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      3:
      - 5
      4: 3.8.10
      5: 0.12.16
      8:
      - 5
backbone:
  desc: null
  value: r101
batch_size:
  desc: null
  value: 32
crop_size:
  desc: null
  value: 256
ignore_bg:
  desc: null
  value: false
keep_ratio:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.8
weight_decay:
  desc: null
  value: 0.01
