wandb_version: 1

backbone:
  value: r50
batch_size:
  value: 32
crop_size:
  value: 256
ignore_bg:
  value: false
keep_ratio:
  value: false
learning_rate:
  value: 0.1
momentum:
  value: 0.8
weight_decay:
  value: 0.01
