wandb_version: 1

backbone:
  value: r101
batch_size:
  value: 4
crop_size:
  value: 256
ignore_bg:
  value: true
keep_ratio:
  value: false
learning_rate:
  value: 0.01
momentum:
  value: 0.9
weight_decay:
  value: 1.0e-08
