wandb_version: 1

backbone:
  value: r50
batch_size:
  value: 16
crop_size:
  value: 512
ignore_bg:
  value: true
keep_ratio:
  value: true
learning_rate:
  value: 0.01
momentum:
  value: 0.8
weight_decay:
  value: 0.0001
