wandb_version: 1

backbone:
  value: r101
batch_size:
  value: 16
crop_size:
  value: 256
ignore_bg:
  value: false
keep_ratio:
  value: true
learning_rate:
  value: 0.0001
momentum:
  value: 0.95
weight_decay:
  value: 0.0001
