wandb_version: 1

backbone:
  value: r101
batch_size:
  value: 8
crop_size:
  value: 512
ignore_bg:
  value: false
keep_ratio:
  value: false
learning_rate:
  value: 0.001
momentum:
  value: 0.95
weight_decay:
  value: 1.0e-08
