wandb_version: 1

backbone:
  value: r50
batch_size:
  value: 32
crop_size:
  value: 512
ignore_bg:
  value: true
keep_ratio:
  value: false
learning_rate:
  value: 1
momentum:
  value: 0.9
weight_decay:
  value: 0.01
