wandb_version: 1

backbone:
  value: w18
batch_size:
  value: 4
crop_size:
  value: 512
ignore_bg:
  value: true
keep_ratio:
  value: false
learning_rate:
  value: 0.01
momentum:
  value: 0.9
weight_decay:
  value: 0.0001
