wandb_version: 1

backbone:
  value: r50
batch_size:
  value: 4
crop_size:
  value: 512
ignore_bg:
  value: ''
keep_ratio:
  value: ''
learning_rate:
  value: 0.1
momentum:
  value: 0.9
weight_decay:
  value: 1.0e-08
