wandb_version: 1

backbone:
  value: r50
batch_size:
  value: 32
crop_size:
  value: 512
ignore_bg:
  value: ''
keep_ratio:
  value: true
learning_rate:
  value: 0.01
momentum:
  value: 0.9
weight_decay:
  value: 1.0e-08
