wandb_version: 1

backbone:
  value: w18
batch_size:
  value: 32
crop_size:
  value: 512
ignore_bg:
  value: true
keep_ratio:
  value: false
learning_rate:
  value: 0.01
momentum:
  value: 0.95
weight_decay:
  value: 1.0e-08
