wandb_version: 1

backbone:
  value: w48
batch_size:
  value: 8
crop_size:
  value: 1024
ignore_bg:
  value: false
keep_ratio:
  value: false
learning_rate:
  value: 0.01
momentum:
  value: 0.95
weight_decay:
  value: 0.0001
