wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1655200094
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      - 60
      2:
      - 1
      - 37
      - 41
      - 55
      - 60
      3:
      - 2
      - 5
      4: 3.8.10
      5: 0.12.18
      8:
      - 5
backbone:
  desc: null
  value: r50
batch_size:
  desc: null
  value: 32
crop_size:
  desc: null
  value: 1024
ignore_bg:
  desc: null
  value: true
keep_ratio:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.95
weight_decay:
  desc: null
  value: 0.0001
