wandb_version: 1

backbone:
  value: r50
batch_size:
  value: 32
crop_size:
  value: 1024
ignore_bg:
  value: true
keep_ratio:
  value: true
learning_rate:
  value: 0.001
momentum:
  value: 0.95
weight_decay:
  value: 1.0e-08
