wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1656582355
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      - 60
      4: 3.8.10
      5: 0.12.18
      8:
      - 5
