wandb_version: 1

backbone:
  value: w18
batch_size:
  value: 8
crop_size:
  value: 512
ignore_bg:
  value: true
keep_ratio:
  value: ''
learning_rate:
  value: 0.1
momentum:
  value: 0.9
weight_decay:
  value: 1.0e-08
