wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1654758017
    t:
      1:
      - 1
      - 37
      - 41
      - 55
      2:
      - 1
      - 37
      - 41
      - 55
      3:
      - 2
      - 5
      4: 3.8.10
      5: 0.12.16
      8:
      - 5
backbone:
  desc: null
  value: r50
batch_size:
  desc: null
  value: 4
crop_size:
  desc: null
  value: 1024
ignore_bg:
  desc: null
  value: true
keep_ratio:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0001
