wandb_version: 1

backbone:
  value: w48
batch_size:
  value: 32
crop_size:
  value: 1024
ignore_bg:
  value: true
keep_ratio:
  value: true
learning_rate:
  value: 0.001
momentum:
  value: 0.8
weight_decay:
  value: 0.01
