wandb_version: 1

backbone:
  value: w48
batch_size:
  value: 32
crop_size:
  value: 256
ignore_bg:
  value: true
keep_ratio:
  value: false
learning_rate:
  value: 0.0001
momentum:
  value: 0.8
weight_decay:
  value: 0.01
