wandb_version: 1

backbone:
  value: w48
batch_size:
  value: 16
crop_size:
  value: 1024
ignore_bg:
  value: true
keep_ratio:
  value: true
learning_rate:
  value: 0.01
momentum:
  value: 0.9
weight_decay:
  value: 0.01
